### ISSUE TITLE
ValueError: Floating point image RGB values must be in the 0..1 range.

### ISSUE THREAD

**Issue by iMiffy** [AyushExel/Neural-Style-Transfer#1]
Hello, thank you so much for the very efficient algo. I am currently facing an error in the last line of the code; it fails to save the image because of range issues. Specifically this line: plt.imsave(str(i)+'.png',imcnvt(target),format='png'). I did not change the normalisation mean and std, if that helps. Thanks again!

**Comment by peakpwr** [comment]
Same issue here

**Comment by Kaoutar142** [comment]
Same issue :(

**Comment by Sush-Sri** [comment]
same issue

**Comment by Sush-Sri** [comment]
same issue

**Comment by raayraay69** [comment]
I want to try this code has the issue been resolved im not sure if i want to dive into this if not

**Comment by aekasitt** [comment]
I managed to fix the issue using `np.clip` since you can convert tensor object back to np.array with min/max pre-defined using this.

My solution is either changing `imcnvt` method to return line as so:
```
  return np.clip(x, 0, 1)
```

or you can just change the final line of the script to

```
  plt.imsave(..., np.clip(imcnvt(target), 0, 1), format='png')
```

But the second method will not remove the matplotlib's warning as followed:
`Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers)`
when calling `plt.imshow`

**Comment by AyushExel** [comment]
Closing this as it is fixed
